apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: fuseki-cache
  name: fuseki-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fuseki-cache
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: fuseki-cache
    spec:
      containers:
        - image: varnish
          name: skosmos-fuseki-cache
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /etc/varnish/default.vcl
              name: fuseki-cache-claim0
      hostname: fuseki-cache
      restartPolicy: Always
      volumes:
        - name: fuseki-cache-claim0
          persistentVolumeClaim:
            claimName: fuseki-cache-claim0
status: {}
