apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: fuseki-cache
  name: fuseki-cache
spec:
  ports:
    - name: "9031"
      port: 9031
      targetPort: 80
  selector:
    io.kompose.service: fuseki-cache
status:
  loadBalancer: {}
