apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: fuseki
  name: fuseki
spec:
  ports:
    - name: "9030"
      port: 9030
      targetPort: 3030
  selector:
    io.kompose.service: fuseki
status:
  loadBalancer: {}
